// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SistemaF.Infrastructure.Persistence;

#nullable disable

namespace SistemaF.Infrastructure.Persistence.Migrations;

[DbContext(typeof(SistemaFDbContext))]
partial class SistemaFDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("dbo")
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        // La snapshot completa viene rigenerata automaticamente
        // da EF Core la prima volta che si esegue:
        //   dotnet ef migrations add <NomeMigrazione>
        // Non modificare questo file manualmente.
#pragma warning restore 612, 618
    }
}
